name: Build from pull request

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - {name: loki-promtail, version: 2.6.1, url: "https://github.com/grafana/loki/releases/download/vVERSION/promtail-linux-arm.zip", binary: promtail, arch: armel}
          - {name: loki-promtail, version: 2.6.1, url: "https://github.com/grafana/loki/releases/download/vVERSION/promtail-linux-arm64.zip", binary: promtail, arch: arm64}
          - {name: prometheus-node-exporter, version: 1.3.1, url: "https://github.com/prometheus/node_exporter/releases/download/vVERSION/node_exporter-VERSION.linux-armv5.tar.gz", binary: node_exporter, arch: armel}
          - {name: prometheus-node-exporter, version: 1.3.1, url: "https://github.com/prometheus/node_exporter/releases/download/vVERSION/node_exporter-VERSION.linux-arm64.tar.gz", binary: node_exporter, arch: arm64}
          - {name: prometheus-cumulus-exporter, version: 0.1.4, url: "https://github.com/tynany/cumulus_exporter/releases/download/vVERSION/cumulus_exporter-VERSION.linux-armv5.tar.gz", binary: cumulus_exporter, arch: armel}
          - {name: prometheus-cumulus-exporter, version: 0.1.4, url: "https://github.com/tynany/cumulus_exporter/releases/download/vVERSION/cumulus_exporter-VERSION.linux-arm64.tar.gz", binary: cumulus_exporter, arch: arm64}
          - {name: prometheus-frr-exporter, version: 0.1.2, url: "https://github.com/tynany/frr_exporter/releases/download/vVERSION/frr_exporter-VERSION.linux-armv5.tar.gz", binary: frr_exporter, arch: armel}
          - {name: prometheus-frr-exporter, version: 0.1.2, url: "https://github.com/tynany/frr_exporter/releases/download/vVERSION/frr_exporter-VERSION.linux-arm64.tar.gz", binary: frr_exporter, arch: arm64}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: prepare package
        run: |
          cp -r src/${{ matrix.package.name }} .debpkg-${{ matrix.package.name }}-${{ matrix.package.arch }}
          bin/fetch.sh ${{ matrix.package.url }} ${{ matrix.package.version }} .debpkg-${{ matrix.package.name }}-${{ matrix.package.arch }} ${{ matrix.package.binary }}

      - uses: jiro4989/build-deb-action@v2
        with:
          package: ${{ matrix.package.name }}
          package_root: .debpkg-${{ matrix.package.name }}-${{ matrix.package.arch }}
          maintainer: MetalStack
          version: ${{ matrix.package.version }}
          arch: ${{ matrix.package.arch }}
          desc: ${{ matrix.package.name }}
      - name: prepare deploy
        run: |
          mkdir -p deploy
          cp *.deb deploy/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          clean: false
          force: false
